### ISSUE TITLE
Reduce number of asserts in the testXTEParserTalkerId method

### ISSUE THREAD

**Issue by vinicius-lemos** [ktuukkan/marine-api#143]
Hi,
PMD identified a problem in the `testXTEParserTalkerId` method. The method contains many asserts, which can make the test complex and difficult to verify. This harms code quality and long-term maintainability.

**Suggestion:**
I suggest splitting the `testXTEParserTalkerId` method into several shorter test methods, each containing a single assert. This would make tests more readable and easier to maintain.

Complex tests can be difficult to understand and increase the workload of the development team. Breaking down tests into smaller scenarios will make maintenance and quality assurance easier.

**Example of Change:**
@Test
public void testXTEParserTalkerId_TalkerId() {
     assertEquals(TalkerId.GP, empty.getTalkerId());
}

@Test
public void testXTEParserTalkerId_SentenceId() {
     assertEquals(SentenceId.XTE.name(), empty.getSentenceId());
}

...

I am willing to work on implementing this change. I look forward to your comments and guidance.

**Comment by ktuukkan** [comment]
In general, I'd agree if the test case was somehow more complex. But these are rather trivial asserts that simply ensure that constructor sets the correct initial values. Hence, I fail to see the point and actual improvement this would bring in.

PMD is a good tool providing suggestions, but instead of blindly following every rule, one should always take the time and consider the findings in contrast to practicality and what the inspected code actually does.
